### ISSUE TITLE
data versions

### ISSUE THREAD

**Issue by YojanaGadiya** [SeonghwanSeo/DeepDL#4]
Dera @SeonghwanSeo,

This is an amazing model and data repo. I was wondering if you could share the versions of the different data you are using. For eg. you mentioned you used ZINC15. Similarily a line about the ChEMBL, PubChem and other versions might be really helpful.

Thank You.

Regards,
Yojana Gadiya

**Comment by SeonghwanSeo** [comment]
Dear Yojana,

I apologize for the delayed response; I missed this issue.

We have already uploaded all versions and weights of models and datasets utilized in our experiments in the manuscript. Could you please clarify what you mean by 'version'?

I will follow up on this issue and aim to respond promptly.

Best regards,
Seonghwan Seo

**Comment by YojanaGadiya** [comment]
Hello @SeonghwanSeo,

No worried on the late response. It is holiday season after all. In the manuscript, you did mention that you use different data resources but the exact version I.e did you train using ChEMBL version 32 or 33 is missing. Similar is the case with PubChem. I was just curious on that end.

Regards,
Yojana Gadiya

**Comment by SeonghwanSeo** [comment]
Hello @YojanaGadiya 

Since data download was not my contribute and the original downloaded files are removed, so I can't find the exact version.
However, I think the version of the ChEMBL database is 28 (expected), or maybe 27.
For PubChem, to the best of my memory, the number of PubChem Compound Database did not change from when I downloaded it, I think it is same to now.

Regards,
Seonghwan Seo

**Comment by YojanaGadiya** [comment]
Hey @SeonghwanSeo,

Thanks, that makes sense.

Regards,
Yojana Gadiya
